'use strict';
let strBtn = document.querySelector("[id='start']"),
    budget = document.querySelectorAll('.budget-value'),
    daybudget = document.querySelectorAll('.daybudget-value'),
    level = document.querySelectorAll('.level-value'),
    expenses = document.querySelectorAll('.expenses-value'),
    optionalexpenses = document.querySelectorAll('.optionalexpenses-value'),
    income = document.querySelectorAll('.income-value'),
    monthsavings = document.querySelectorAll('.monthsavings-value'),
    yearsavings = document.querySelectorAll('.yearsavings-value'),
    year = document.querySelectorAll('.year-value'),
    month = document.querySelectorAll('.month-value'),
    day = document.querySelectorAll('.day-value'),
    expensesItem = document.querySelectorAll('.expenses-item'),
    expensesBtn = document.getElementsByTagName("button")[0],
    optionalExpensesBtn = document.getElementsByTagName("button")[1],
    countBtn = document.getElementsByTagName("button")[2],
    optExpensesItem = document.querySelectorAll(".optionalexpenses-item"),
    chooseIncome = document.querySelector(".choose-income"),
    haveSavings = document.querySelector("#savings"),
    sumValue = document.querySelector("#sum"),
    percentValue = document.querySelector("#percent"),
    yearValue = document.querySelector(".year-value"),
    monthValue = document.querySelector(".month-value"),
    dayValue = document.querySelector(".day-value");
